-- spring-durable-agents schema, H2 (tests and local development)

create table agent_run (
    id              varchar(26)  primary key,
    agent_name      varchar(200) not null,
    agent_version   integer      not null,
    status          varchar(20)  not null,
    input           text,
    output          text,
    error           text,
    created_at      timestamp with time zone not null,
    updated_at      timestamp with time zone not null,
    owner_instance  varchar(200),
    lease_until     timestamp with time zone,
    correlation_id  varchar(200)
);

create index agent_run_status_lease_idx on agent_run (status, lease_until);
create index agent_run_agent_created_idx on agent_run (agent_name, created_at desc);
create index agent_run_correlation_idx on agent_run (correlation_id);

create table agent_step (
    id            bigint generated by default as identity primary key,
    run_id        varchar(26)  not null references agent_run (id) on delete cascade,
    step_key      varchar(400) not null,
    step_name     varchar(200) not null,
    step_version  integer      not null,
    sequence      integer      not null,
    status        varchar(20)  not null,
    attempt       integer      not null,
    input         text,
    output        text,
    output_type   varchar(400),
    error         text,
    kind          varchar(20)  not null,
    parent_key    varchar(400),
    tokens_in     bigint,
    tokens_out    bigint,
    model         varchar(200),
    started_at    timestamp with time zone,
    finished_at   timestamp with time zone,
    constraint agent_step_run_key_uq unique (run_id, step_key)
);

create index agent_step_run_sequence_idx on agent_step (run_id, sequence);

create table agent_approval (
    id             varchar(26)  primary key,
    run_id         varchar(26)  not null references agent_run (id) on delete cascade,
    step_key       varchar(400) not null,
    required_role  varchar(100) not null,
    description    text,
    requested_at   timestamp with time zone not null,
    expires_at     timestamp with time zone not null,
    decision       varchar(20)  not null,
    decided_at     timestamp with time zone,
    decided_by     varchar(200),
    comment        text
);

create index agent_approval_pending_idx on agent_approval (decision, required_role, expires_at);
create index agent_approval_run_idx on agent_approval (run_id, step_key);
